name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/deployer:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: SerheyJankowsky/ssh-action@v1
        with:
          ssh_host: ${{ secrets.SSH_HOST }}
          ssh_user: ${{ secrets.SSH_USER }}
          # ssh-port: ${{ secrets.SSH_PORT }}
          ssh_password: ${{ secrets.SSH_PASSWORD }}
          env-vars: "SSH_HOST,SSH_USER,SSH_PASSWORD,DOCKER_USERNAME,DOCKER_PASSWORD"
          script: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker pull $DOCKER_USERNAME/deployer:latest
            docker stop deployer
            docker rm deployer
            cp $ENVS .env
            docker run -d --name deployer --env-file .env $DOCKER_USERNAME/deployer:latest
            rm -rf .env
