name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/deployer:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: SerheyJankowsky/ssh-action@v1
        with:
          ssh_host: ${{ secrets.SSH_HOST }}
          ssh_user: ${{ secrets.SSH_USER }}
          # ssh-port: ${{ secrets.SSH_PORT }}
          ssh_password: ${{ secrets.SSH_PASSWORD }}
          script: |
            echo "Deploying to server...."
            echo "Logging in to Docker Hub..."
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            echo "Pulling latest image..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/deployer:latest
            echo "Stopping existing container..."
            docker stop deployer || true
            echo "Removing existing container..."
            docker rm deployer || true
            echo "Copying environment variables..."
            echo "ENVS: ${{ secrets.ENVS }}"
            cp ${{ secrets.ENVS }} .env
            docker run -d --name deployer --env-file .env ${{ secrets.DOCKER_USERNAME }}/deployer:latest
            rm -rf .env
