name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/deployer:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      SERVER_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      SERVER_HOST: ${{ secrets.SSH_HOST }}
      SERVER_USER: ${{ secrets.SSH_USER }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      ENVS: ${{ secrets.ENVS }}
    steps:
      - name: Install SSH tools
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass openssh-client
      - name: Deploy to server
        run: |
          mkdir -p ~/.ssh
          echo "Host *" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          echo "  UserKnownHostsFile /dev/null" >> ~/.ssh/config
          chmod 600 ~/.ssh/config

          # Execute deployment commands on remote server
          sshpass -p "$SERVER_PASSWORD" ssh $SERVER_USER@$SERVER_HOST << 'EOF'
          echo "Deploying to server...."
          echo "Logging in to Docker Hub..."
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          echo "Pulling latest image..."
          docker pull $DOCKER_USERNAME/deployer:latest
          echo "Stopping existing container..."
          docker stop deployer || true
          echo "Removing existing container..."
          docker rm deployer || true
          echo "Copying environment variables..."
          echo $ENVS > .env
          echo "Running container..."
          docker run -d --name deployer --env-file .env $DOCKER_USERNAME/deployer:latest --restart unless-stopped --network gateway_network --ip 172.30.0.20
          echo "Removing environment variables..."
          rm -rf .env
          EOF
